name: Git Tag Test

on:
  # pull_request:
  #   branches:
  #     - "**"
  # pull_request:
  #   types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: >
          Tag Version
        required: false

jobs:
  call_git_tag_rel:
    name: Call Git Tag Rel
    uses: ./.github/workflows/git-tag-rel.yml
    with:
      version: ${{ github.event.inputs.version }}
